project_name: cosign

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

# Prevents parallel builds from stepping on eachothers toes downloading modules
before:
  hooks:
  - go mod tidy

builds:
- id: linux
  binary: cosign
  main: ./cmd/cosign
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - "{{ .Env.LDFLAGS }}"
  env:
    - CGO_ENABLED=0

- id: linux-pivkey-amd64
  binary: cosign-pivkey
  main: ./cmd/cosign
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - "{{ .Env.LDFLAGS }}"
  tags:
    - pivkey
  hooks:
    pre:
      - apt-get update
      - apt-get -y install libpcsclite-dev
  env:
    - PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/"

- id: darwin-amd64
  binary: cosign
  env:
    - CC=o64-clang
    - CXX=o64-clang++
  main: ./cmd/cosign
  goos:
    - darwin
  goarch:
    - amd64
  ldflags:
    - "{{ .Env.LDFLAGS }}"
  tags:
    - pivkey

- id: darwin-arm64
  binary: cosign
  env:
    - CC=aarch64-apple-darwin20.2-clang
    - CXX=aarch64-apple-darwin20.2-clang++
  main: ./cmd/cosign
  goos:
    - darwin
  goarch:
    - arm64
  tags:
    - pivkey
  ldflags:
    - "{{.Env.LDFLAGS}}"

- id: windows-amd64
  binary: cosign
  env:
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  main: ./cmd/cosign
  goos:
    - windows
  goarch:
    - amd64
  ldflags:
    - -buildmode=exe
    - "{{ .Env.LDFLAGS }}"
  tags:
    - pivkey

- id: linux-cosigned
  binary: cosigned
  main: ./cmd/cosign/webhook
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - "{{ .Env.LDFLAGS }}"
  env:
    - CGO_ENABLED=0

- id: sget
  binary: sget
  main: ./cmd/sget
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ignore:
    - goos: windows
      goarch: arm64
  ldflags:
    - "{{ .Env.LDFLAGS }}"
  env:
    - CGO_ENABLED=0

signs:
  - id: cosign
    signature: "${artifact}.sig"
    cmd: ./dist/cosign-linux-amd64
    args: ["sign-blob", "--output", "${artifact}.sig", "--key", "gcpkms://projects/{{ .Env.PROJECT_ID }}/locations/{{ .Env.KEY_LOCATION }}/keyRings/{{ .Env.KEY_RING }}/cryptoKeys/{{ .Env.KEY_NAME }}/versions/{{ .Env.KEY_VERSION }}", "${artifact}"]
    artifacts: binary
  - id: cosigned
    signature: "${artifact}.sig"
    cmd: ./dist/cosign-linux-amd64
    args: ["sign-blob", "--output", "${artifact}.sig", "--key", "gcpkms://projects/{{ .Env.PROJECT_ID }}/locations/{{ .Env.KEY_LOCATION }}/keyRings/{{ .Env.KEY_RING }}/cryptoKeys/{{ .Env.KEY_NAME }}/versions/{{ .Env.KEY_VERSION }}", "${artifact}"]
    artifacts: binary
    ids:
      - linux-cosigned
  - id: sget
    signature: "${artifact}.sig"
    cmd: ./dist/cosign-linux-amd64
    args: ["sign-blob", "--output", "${artifact}.sig", "--key", "gcpkms://projects/{{ .Env.PROJECT_ID }}/locations/{{ .Env.KEY_LOCATION }}/keyRings/{{ .Env.KEY_RING }}/cryptoKeys/{{ .Env.KEY_NAME }}/versions/{{ .Env.KEY_VERSION }}", "${artifact}"]
    artifacts: binary
    ids:
      - sget

dockers:
  # cosign Image
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/cosign:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/cosign:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=arm64"

  # cosigned Image
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/cosigned:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.cosigned
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/cosigned:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.cosigned
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=arm64"

  # sget Image
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/sget:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.sget
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=amd64"
  - image_templates:
      - "ghcr.io/{{ .Env.PROJECT_ID }}/sget:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.sget
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=RUNTIME_IMAGE={{ .Env.RUNTIME_IMAGE }}"
      - "--build-arg=ARCH=arm64"

docker_manifests:
  - name_template: ghcr.io/{{ .Env.PROJECT_ID }}/cosign:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.PROJECT_ID }}/cosign:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.PROJECT_ID }}/cosign:{{ .Version }}-arm64v8
  - name_template: ghcr.io/{{ .Env.PROJECT_ID }}/cosigned:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.PROJECT_ID }}/cosigned:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.PROJECT_ID }}/cosigned:{{ .Version }}-arm64v8
  - name_template: ghcr.io/{{ .Env.PROJECT_ID }}/sget:{{ .Version }}
    image_templates:
      - ghcr.io/{{ .Env.PROJECT_ID }}/sget:{{ .Version }}-amd64
      - ghcr.io/{{ .Env.PROJECT_ID }}/sget:{{ .Version }}-arm64v8

docker_signs:
  - artifacts: all
    args: [ "sign", "--key", "gcpkms://projects/{{ .Env.PROJECT_ID }}/locations/{{ .Env.KEY_LOCATION }}/keyRings/{{ .Env.KEY_RING }}/cryptoKeys/{{ .Env.KEY_NAME }}/versions/{{ .Env.KEY_VERSION }}", "${artifact}" ]

archives:
- format: binary
  name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  allow_different_binary_count: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  prerelease: allow # remove this when we start publishing non-prerelease or set to auto
  draft: true # allow for manual edits
  github:
    owner: sigstore
    name: cosign
  footer: |
    ### Thanks for all contributors!

  extra_files:
    - glob: "./release/release-cosign.pub"
