apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cosigned.fullname" . }}-webhook
  labels:
    {{- include "cosigned.labels" . | nindent 4 }}
    control-plane: {{ template "cosigned.fullname" . }}-webhook
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["list", "get", "watch", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs: ["list", "get", "watch", "create", "update", "delete"]
