apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- if .Values.webhook.service.annotations }}
    {{ toYaml .Values.webhook.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "cosigned.labels" . | nindent 4 }}
    control-plane: {{ template "cosigned.fullname" . }}-webhook
  name: {{ template "cosigned.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  type: {{.Values.webhook.service.type}}
  ports:
  - name: https
    port: {{ .Values.webhook.service.port }}
    protocol: TCP
    targetPort: https
    {{- if and .Values.webhook.service.nodePort (eq "NodePort" .Values.webhook.service.type) }}
    nodePort: {{ .Values.webhook.service.nodePort }}
    {{- end }}
  selector:
    {{- include "cosigned.selectorLabels" . | nindent 4 }}
    control-plane: {{ template "cosigned.fullname" . }}-webhook
