#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s

steps:
- name: gcr.io/cloud-builders/git
  dir: "go/src/sigstore"
  args:
  - "clone"
  - "https://github.com/${_TOOL_ORG}/${_TOOL_REPO}"

- name: gcr.io/cloud-builders/git
  entrypoint: "bash"
  dir: "go/src/sigstore/cosign"
  args:
  - '-c'
  - |
    git fetch
    echo "Checking out ${_GIT_TAG}"
    git checkout ${_GIT_TAG}

- name: 'gcr.io/projectsigstore/cosign:v1.10.0@sha256:a719237925984033fb72685c1998d922c903bbe62464f6d401b5108d3195bb94'
  dir: "go/src/sigstore/cosign"
  env:
  - COSIGN_EXPERIMENTAL=true
  - TUF_ROOT=/tmp
  args:
  - 'verify'
  - 'ghcr.io/gythialy/golang-cross:v1.18.5-0@sha256:126d3f66ba180363ea97eac070a7e6f51b4ba5b6172eb50afd79f9ad92874e72'

# maybe we can build our own image and use that to be more in a safe side
- name: ghcr.io/gythialy/golang-cross:v1.18.5-0@sha256:126d3f66ba180363ea97eac070a7e6f51b4ba5b6172eb50afd79f9ad92874e72
  entrypoint: /bin/sh
  dir: "go/src/sigstore/cosign"
  env:
  - "GOPATH=/workspace/go"
  - "GOBIN=/workspace/bin"
  - PROJECT_ID=${PROJECT_ID}
  - KEY_LOCATION=${_KEY_LOCATION}
  - KEY_RING=${_KEY_RING}
  - KEY_NAME=${_KEY_NAME}
  - KEY_VERSION=${_KEY_VERSION}
  - GIT_TAG=${_GIT_TAG}
  - GOOGLE_SERVICE_ACCOUNT_NAME=keyless@${PROJECT_ID}.iam.gserviceaccount.com
  - COSIGN_EXPERIMENTAL=true
  - KO_PREFIX=gcr.io/${PROJECT_ID}
  secretEnv:
  - GITHUB_TOKEN
  args:
    - '-c'
    - |
      gcloud auth configure-docker \
      && make release

- name: ghcr.io/gythialy/golang-cross:v1.18.5-0@sha256:126d3f66ba180363ea97eac070a7e6f51b4ba5b6172eb50afd79f9ad92874e72
  entrypoint: 'bash'
  dir: "go/src/sigstore/cosign"
  env:
  - "GOPATH=/workspace/go"
  - "GOBIN=/workspace/bin"
  - PROJECT_ID=${PROJECT_ID}
  - KEY_LOCATION=${_KEY_LOCATION}
  - KEY_RING=${_KEY_RING}
  - KEY_NAME=${_KEY_NAME}
  - KEY_VERSION=${_KEY_VERSION}
  - GIT_TAG=${_GIT_TAG}
  - KO_PREFIX=gcr.io/${PROJECT_ID}
  - COSIGN_EXPERIMENTAL=true
  - GOOGLE_SERVICE_ACCOUNT_NAME=keyless@${PROJECT_ID}.iam.gserviceaccount.com
  - GITHUB_USER=${_GITHUB_USER}
  secretEnv:
  - GITHUB_TOKEN
  args:
    - '-c'
    - |
      echo $$GITHUB_TOKEN | docker login ghcr.io -u $$GITHUB_USER --password-stdin \
      && make copy-signed-release-to-ghcr || true

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_NUMBER}/secrets/GITHUB_TOKEN/versions/latest
    env: GITHUB_TOKEN

artifacts:
  objects:
    location: 'gs://${_STORAGE_LOCATION}/${_GIT_TAG}'
    paths:
    - "go/src/sigstore/cosign/dist/*"
    - "go/src/sigstore/cosign/release/release-cosign.pub"

options:
  machineType: E2_HIGHCPU_32

tags:
- cosign-release
- ${_GIT_TAG}
- ${_TOOL_ORG}
- ${_TOOL_REPO}

substitutions:
  _GIT_TAG: 'v1.23.45'
  _TOOL_ORG: 'honk'
  _TOOL_REPO: 'honk-repo'
  _STORAGE_LOCATION: 'honk'
  _KEY_RING: 'honk-ring'
  _KEY_NAME: 'honk-crypto'
  _KEY_VERSION: '1'
  _KEY_LOCATION: 'global'
  _GITHUB_USER: 'placeholder'
