#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s

steps:
- name: gcr.io/cloud-builders/git
  dir: "go/src/sigstore"
  args:
  - "clone"
  - "https://github.com/${_TOOL_ORG}/${_TOOL_REPO}"

- name: gcr.io/cloud-builders/git
  entrypoint: "bash"
  dir: "go/src/sigstore/cosign"
  args:
  - '-c'
  - |
    git fetch
    echo "Checking out ${_TOOL_REF}"
    git checkout ${_TOOL_REF}

# maybe we can build our own image and use that to be more in a safe side
- name: ghcr.io/gythialy/golang-cross:v1.16.5@sha256:5874d76072f0d434b4328c77977f1a9fb9bf28b21f083cf1b9a53ec497656128
  entrypoint: /bin/sh
  dir: "go/src/sigstore/cosign"
  env:
  - "GOPATH=/workspace/go"
  - "GOBIN=/workspace/bin"
  - PROJECT_ID=${PROJECT_ID}
  - KEY_LOCATION=${_KEY_LOCATION}
  - KEY_RING=${_KEY_RING}
  - KEY_NAME=${_KEY_NAME}
  - KEY_VERSION=${_KEY_VERSION}
  secretEnv:
  - GITHUB_TOKEN
  args:
    - '-c'
    - |
      git tag ${_GIT_TAG}
      make release

- name: gcr.io/cloud-builders/docker
  entrypoint: "bash"
  dir: "go/src/sigstore/cosign"
  env:
  - GIT_TAG=${_GIT_TAG}
  - PROJECT_ID=${PROJECT_ID}
  - KEY_LOCATION=${_KEY_LOCATION}
  - KEY_RING=${_KEY_RING}
  - KEY_NAME=${_KEY_NAME}
  - KEY_VERSION=${_KEY_VERSION}
  - RUNTIME_IMAGE=${_RUNTIME_IMAGE}
  args:
  - '-c'
  - |
    apt-get update
    apt-get install libpcsclite-dev -y
    cp ./dist/cosign-linux-amd64 /usr/local/bin/cosign
    cosign verify-dockerfile -base-image-only -key https://raw.githubusercontent.com/GoogleContainerTools/distroless/main/cosign.pub ./Dockerfile
    make sign-container-cloudbuild

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_NUMBER}/secrets/GITHUB_TOKEN/versions/latest
    env: GITHUB_TOKEN

artifacts:
  objects:
    location: 'gs://${_STORAGE_LOCATION}/${_GIT_TAG}'
    paths:
    - "go/src/sigstore/cosign/dist/cosign*"
    - "go/src/sigstore/cosign/release/release-cosign.pub"

options:
  machineType: E2_HIGHCPU_8

tags:
- cosign-release
- ${_GIT_TAG}
- ${_TOOL_ORG}
- ${_TOOL_REPO}
- ${_TOOL_REF}

substitutions:
  _GIT_TAG: 'v1.23.45'
  _TOOL_ORG: 'honk'
  _TOOL_REPO: 'honk-repo'
  _TOOL_REF: 'release-honk'
  _STORAGE_LOCATION: 'honk'
  _KEY_RING: 'honk-ring'
  _KEY_NAME: 'honk-crypto'
  _KEY_VERSION: '1'
  _KEY_LOCATION: 'global'
  _RUNTIME_IMAGE: 'gcr.io/distroless/static'
