//
// Copyright 2021 The Sigstore Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generate

import (
	"context"
	"flag"
	"fmt"
	"io"

	"github.com/google/go-containerregistry/pkg/name"
	"github.com/peterbourgon/ff/v3/ffcli"

	"github.com/sigstore/cosign/cmd/cosign/cli/options"
	ociremote "github.com/sigstore/cosign/pkg/oci/remote"
	"github.com/sigstore/cosign/pkg/signature"
	"github.com/sigstore/sigstore/pkg/signature/payload"
)

// Generate subcommand for ffcli.
// Deprecated: this will be deleted when the migration from ffcli to cobra is done.
func Generate() *ffcli.Command {
	var (
		flagset     = flag.NewFlagSet("cosign generate", flag.ExitOnError)
		regOpts     options.RegistryOptions
		annotations = signature.AnnotationsMap{}
	)
	options.ApplyRegistryFlags(&regOpts, flagset)
	flagset.Var(&annotations, "a", "extra key=value pairs to sign")

	return &ffcli.Command{
		Name:       "generate",
		ShortUsage: "cosign generate [-a key=value] <image uri>",
		ShortHelp:  "Generates (unsigned) signature payloads from the supplied container image",
		LongHelp: `Generates an unsigned payload from the supplied container image and flags.
This payload matches the one generated by the "cosign sign" command and can be used if you need
to sign payloads with your own tooling or algorithms.

EXAMPLES
	# Generate a simple payload for an image
	cosign generate <IMAGE>

	# Generate a payload with specific annotations
	cosign generate -a foo=bar <IMAGE>

	# Use this payload in another tool
	gpg --output image.sig --detach-sig <(cosign generate <IMAGE>)`,
		FlagSet: flagset,
		Exec: func(ctx context.Context, args []string) error {
			panic("this command is now implemented in cobra.")
		},
	}
}

// nolint
func GenerateCmd(ctx context.Context, regOpts options.RegistryOptions, imageRef string, annotations map[string]interface{}, w io.Writer) error {
	ref, err := name.ParseReference(imageRef)
	if err != nil {
		return err
	}
	digest, err := ociremote.ResolveDigest(ref, regOpts.ClientOpts(ctx)...)
	if err != nil {
		return err
	}
	// Overwrite "ref" with a digest to avoid a race where we use a tag
	// multiple times, and it potentially points to different things at
	// each access.
	ref = digest

	json, err := (&payload.Cosign{Image: digest, Annotations: annotations}).MarshalJSON()
	if err != nil {
		return err
	}
	fmt.Fprintln(w, string(json))
	return nil
}
