name: CI-Build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: build
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@main
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: install ko
        run: |
          curl -L https://github.com/google/ko/releases/download/v0.8.1/ko_0.8.1_Linux_x86_64.tar.gz | tar xzf - ko && \
          chmod +x ./ko && sudo mv ko /usr/local/bin/

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: projectsigstore
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: creds
        run: gcloud auth configure-docker --quiet

      - name: build
        run: make cross
      - name: container
        run: echo -n "${{secrets.COSIGN_PASSWORD}}" | KO_DOCKER_REPO=gcr.io/projectsigstore/cosign/ci/cosign make sign-container
      - name: Print Info
        run: shasum -a 256 ./cosign-* > cosign.sha256 && cat cosign.sha256
      - name: sign
        run: |
          echo -n "${{secrets.COSIGN_PASSWORD}}" | cosign sign-blob -key ./.github/workflows/cosign.key ././cosign-linux-amd64 > cosign-linux-amd64.sig
          echo -n "${{secrets.COSIGN_PASSWORD}}" | cosign sign-blob -key ./.github/workflows/cosign.key ././cosign-darwin-amd64 > cosign-darwin-amd64.sig
      - name: verify
        run: cosign verify-blob -key ./.github/workflows/cosign.pub -signature cosign-linux-amd64.sig ./cosign-linux-amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            cosign-*
            cosign.-*sha256
            cosign-*.sig
