name: "Close stale issues/pull requests"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@6f05e4244c9a0b2ed3401882b05d701dd0a7289b # v7.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'bug,core feature,enhancement,good first issue,help wanted,needs discussion'
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'awaiting-approval,work-in-progress'
          days-before-pr-stale: '30'
          days-before-pr-close: '10'
          days-before-issue-stale: '60'
          days-before-close: '5'
