#
# Copyright 2024 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Whitespace

on:
  pull_request:
    branches:
      - 'main'
      - 'release-*'

permissions: {}

jobs:

  whitespace:
    name: Check Whitespace
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/trailing-space@a9d4aa7202a63f8a6b8f81bb1570a0ca54460ac5 # v1.6.34
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@a9d4aa7202a63f8a6b8f81bb1570a0ca54460ac5 # v1.6.34
        if: ${{ always() }}
